### ISSUE TITLE
_train_scipy saves loss_train for every step

### ISSUE THREAD

**Issue by smao-astro** [lululxvi/deepxde#130]
Hi Lu,

I found that because of https://github.com/lululxvi/deepxde/blob/61c45e83de5079ca88ad86a3bbfa2871b24ca52e/deepxde/model.py#L236-L238 `_train_scipy` saves `loss_train` for every step it trained, while `_train_sgd` only saves loss_train when https://github.com/lululxvi/deepxde/blob/61c45e83de5079ca88ad86a3bbfa2871b24ca52e/deepxde/model.py#L220-L221, do you think this is the desired behavior?

**Comment by lululxvi** [comment]
Thank you for pointing out this. Because Scipy optimizers (e.g., BFGS) usually finish within much fewer iterations, and thus I decided to save the train loss every step. But SGD needs long iterations, and there is no need to save it every step. This is the desired behavior, but I am not sure whether this is the best choice.

**Comment by smao-astro** [comment]
I see, thank you for explain this.
