### ISSUE TITLE
Neumann boundary condition problem

### ISSUE THREAD

**Issue by Will-abc** [lululxvi/deepxde#303]
Hi Dr. Lu,

I'm using DeepXDE to solve a 2D NS problem with pressure boundary condition dp/dn=0. I defined the rectangular domain and specified the boundary condition by:

```
spatial_domain = dde.geometry.Rectangle(xmin=[0,0], xmax=[1,1])

def boundary_left(x,on_boundary):
  return on_boundary and np.isclose(x[0],0)

bc_p_left = dde.NeumannBC(spatial_domain, lambda x:0, boundary_left, component=2)
```
But the code returned this error:

ValueError: Rectangle: Method `boundary_normal` do not accept points on the vertexes.

Could you help me? Thank you very much!

Will

**Comment by lululxvi** [comment]
The issue is that the normal direction of vertices (e.g., [0,0]) is not well defined. I have fixed the code by returning the averaged direction, e.g., [-0.707, -0.707] for [0,0]. This is not a problem if you sampled a lot of points, because we compute MSE.

But a better way is that you exclude the corners from training points, by using
```python
x = np.array([[0, 0], [0, 1]])
PDE(..., exclusions=x)
```

**Comment by Will-abc** [comment]
Thank you so much, Dr. Lu! It solves my problem.

**Comment by lululxvi** [comment]
The code of returning averaged direction has been added in v0.11.2

**Comment by Will-abc** [comment]
Thank you very much, Dr. Lu! I will update my installation.
