### ISSUE TITLE
The number of CSG operations scaling with time 

### ISSUE THREAD

**Issue by alecjervis1** [lululxvi/deepxde#357]
Hi Lulu,

![plot](https://user-images.githubusercontent.com/79330532/129801103-1513a0e7-24ad-4c40-a7fc-287efa666caa.png)

(Here the different lines are for different numbers of residual points)

When I increase the number of CSG operations to be performed during the training process, in this case by consecutively removing another circle from a square geometry on each training process, the time taken to establish the residual points at the start of training increases quite dramatically. 

I would have expected the time dependence on CSG operations to be linear. I wondered if you had an explanation for this? 

Many thanks in advance,
Alec

**Comment by alecjervis1** [comment]
![train](https://user-images.githubusercontent.com/79330532/129802481-803708c4-98ec-4401-9e53-3d03f6bd61c6.png)

Another issue I am seeing is that when training a PINN with an increasing number of circles removed from the square in 3 different scenarios: constant hyperparameters, linearly increasing epochs and linearly increasing number of residual points - with all three scenarios having the same hyperparameters for the first PINN (with one circle removed from the square)  - I experience higher train times for this first PINN in all three cases. 

Intuitively this first PINN should take the same amount of time as all of the other training processes in the constant hyperparameter scenario, but it doesn't. I wondered if you had any suggestions for what is happening here as well? 

Again, many thanks in advance to anyone with a suggestion!
Alec

**Comment by lululxvi** [comment]
First figure:
- The time to compile contains many steps, including point sampling, building losses, etc.
- Some operations depend linearly on the number of geometries, but some depend on the number of total points, and some depend on the number of boundaries, etc. So total time could depend more than linearly on the number of geometries.
- Most of these operations are implemented as "vectorized" in numpy, but there are still some operations implemented in a naive "for" loop, which is slow. If the compiling time is an issue for your problem, we can discuss how to make it faster.

Second figure:
- The scaling of the three lines looks good.
- For "constant hyperparameter", does it due to that for more channels we have less points?
