### ISSUE TITLE
Giving weights to different residual points

### ISSUE THREAD

**Issue by elhamwasei** [lululxvi/deepxde#45]
Hi!
I've seen how you can give weights to the loss on the boundary conditions and the loss on the PDE. But is there also an easy way to give different weights to different residual points in the domain/on the boundary? Or maybe you can tell me where the loss function (equation 2.2 in the paper) is coded?

**Comment by lululxvi** [comment]
To give different weights to different residual points, unfortunately you have to modify the code. It is not hard, let me know if you want, and I can tell you how to do.

But there are other ways which should be able to have similar effects:

1. The weights are integers. For example, there are two residual points `x1` and `x2`, and I want to set the weight for `x1` to be 2, and the weight for `x2` to be `1`. Then instead of using the dataset `[x1, x2]`, you can choose the dataset `[x1, x1, x2]`, i.e., repeat the residual points according to the weights.

2. You can use the residual-based adaptive refinement (RAR) method to select the residual points more efficiently in a non-uniform way.

**Comment by azhu529** [comment]
Hi @lululxvi,

Do you mind pointing out the relevant code files/changes that need to be made to implement this?

E.g. if I have points [x1, x2] and I want to assign weights [10,1], is there a more efficient method than explicitly writing out 11 points with repeats? That seems resource-intensive (the same goes for RAR); I'd like to use a smaller dataset with weights instead of denser sampling.

Thanks!

**Comment by lululxvi** [comment]
You need to modify the loss:
https://github.com/lululxvi/deepxde/blob/3e6842069e0c377e7b0b80c3b9973bc8001927ae/deepxde/data/pde.py#L125
There are also other ways to do it, e.g., modifying the PDE residual.

**Comment by nirfein** [comment]
@lululxvi @elhamwasei  could you kindly direct me to where i can find instruction on how to apply different weights to loss on boundary conditions than from weights on inner domain loss ?

**Comment by lululxvi** [comment]
See https://deepxde.readthedocs.io/en/latest/modules/deepxde.html#deepxde.model.Model.compile

**Comment by nirfein** [comment]
thank you very much!   is there a way to apply a featured Fourier layer before the rest of the hidden layers ?
