### ISSUE TITLE
Question regarding 'Poisson equation in 1D with Dirichlet/Periodic boundary conditions' 

### ISSUE THREAD

**Issue by mlin26** [lululxvi/deepxde#457]
Hi Prof. Lu,

I just start to learn deepxde. I have a question regarding 1D Poisson equation with Periodic boundary conditions. [https://deepxde.readthedocs.io/en/latest/demos/poisson.1d.dirichletperiodic.html?highlight=periodic](url)

In the problem, the PBC is u(0) = u(1), but in the code, I see that it only considers boundary at x=1, that is u(1). Could you tell me where do we define u(0) here?
`bc2 = dde.PeriodicBC(geom, 0, boundary_r)`

To my understanding, this line code says that the periodic boundary condition is defined at 'boundary_r' in the x-direction. Do we consider u(0) implicitly?

Thanks in advance!

**Comment by lululxvi** [comment]
DeepXDE will automatically find that the periodic location of the right is the left.

**Comment by cubayang** [comment]
Hi Lu,



I also have a question for periodic boundary condition. In the example for Schrodinger problem (shown in the figure), you specify component=0 or 1 for IC, should we also specify component for BC? 
![1640177341(1)](https://user-images.githubusercontent.com/10250229/147096828-18ac0eeb-b66a-4219-98cf-7000eb23d998.png)
To my understanding, BC should be like:

bc_u_0 = dde.PeriodicBC(
    geomtime, 0, lambda _, on_boundary: on_boundary, derivative_order=0, component=0
)
bc_u_1 = dde.PeriodicBC(
    geomtime, 0, lambda _, on_boundary: on_boundary, derivative_order=1, component=0
)
bc_v_0 = dde.PeriodicBC(
    geomtime, 1, lambda _, on_boundary: on_boundary, derivative_order=0, component=1
)
bc_v_1 = dde.PeriodicBC(
    geomtime, 1, lambda _, on_boundary: on_boundary, derivative_order=1, component=1
) 

Thanks in advance!

**Comment by cubayang** [comment]
@lululxvi

**Comment by lululxvi** [comment]
Actually, it should be
```python
bc_u_0 = dde.PeriodicBC(
    geomtime, 0, lambda _, on_boundary: on_boundary, derivative_order=0, component=0
)
bc_u_1 = dde.PeriodicBC(
    geomtime, 0, lambda _, on_boundary: on_boundary, derivative_order=1, component=0
)
bc_v_0 = dde.PeriodicBC(
    geomtime, 0, lambda _, on_boundary: on_boundary, derivative_order=0, component=1
)
bc_v_1 = dde.PeriodicBC(
    geomtime, 0, lambda _, on_boundary: on_boundary, derivative_order=1, component=1
)
```

**Comment by cubayang** [comment]
Thank you for your response. I am still a bit confused about parameters "component_x", I know it's different from "component", but when do we need to specify nonzero values for "component_x"? Thanks!

**Comment by FMagnani** [comment]
In fact, @lululxvi is right, the code should be 

> ```python
> bc_u_0 = dde.PeriodicBC(
>     geomtime, 0, lambda _, on_boundary: on_boundary, derivative_order=0, component=0
> )
> bc_u_1 = dde.PeriodicBC(
>     geomtime, 0, lambda _, on_boundary: on_boundary, derivative_order=1, component=0
> )
> bc_v_0 = dde.PeriodicBC(
>     geomtime, 0, lambda _, on_boundary: on_boundary, derivative_order=0, component=1
> )
> bc_v_1 = dde.PeriodicBC(
>     geomtime, 0, lambda _, on_boundary: on_boundary, derivative_order=1, component=1
> )
> ```

I really apologize for the mistake.   
  
In dde.PeriodicBC, the second argument (component_x) specifies:  
- The direction to which periodicity applies
- The input component with respect to which the jacobian is computed (In the case that derivative_order=1)  
  
In the Schrodinger example, the input is given as (x,t) so "component_x" should always be 0.  
The argument "component" specifies:
- The output component to which the Boundary Condition applies
- The output component to be derivated with respect to "component_x "  (In the case derivative_order=1)
  
So in the example, "component" should be 0 for the conditions referring to *u* and it should be 1 for the conditions  referring to *v*.  
  
In this particular case, the Boundary Conditions are not highly involved in the training since the solution is identically zero on the boundaries for each t. Therefore the solution is not affected by the mistake. In a general case however, the outcome would have been totally wrong!  
  

@cubayang 
> Thank you for your response. I am still a bit confused about parameters "component_x", I know it's different from "component", but when do we need to specify nonzero values for "component_x"? Thanks!  
  
In the example, the 1-dimensional Schrodinger equation has been considered. In problems with more than one spatial dimensions the "component_x" argument is needed.

**Comment by tuzu123** [comment]
> Hi Prof. Lu,
> 
> I just start to learn deepxde. I have a question regarding 1D Poisson equation with Periodic boundary conditions. [https://deepxde.readthedocs.io/en/latest/demos/poisson.1d.dirichletperiodic.html?highlight=periodic](url)
> 
> In the problem, the PBC is u(0) = u(1), but in the code, I see that it only considers boundary at x=1, that is u(1). Could you tell me where do we define u(0) here? `bc2 = dde.PeriodicBC(geom, 0, boundary_r)`
> 
> To my understanding, this line code says that the periodic boundary condition is defined at 'boundary_r' in the x-direction. Do we consider u(0) implicitly?
> 
> Thanks in advance!

Hello @mlin26 
At first, I am also confused about the periodic condition of u(0) = u(1) until seeing the problem"What's the PDE problem for Poisson_periodic_1d.py ? #51"
So I think the code is correct, the problem comes from the mathematical formula. In fact, the x belongs to [-1,1], so the left boundary is x = -1, so the correct formula should be u(-1)=u(1). I hope it will help you to understand the periodicBC. 

I hope that I am not misunderstanding the formula in https://deepxde.readthedocs.io/en/latest/demos/pinn_forward/poisson.1d.dirichletperiodic.html
@lululxvi
