### ISSUE TITLE
Time-dependent Boundary Conditions

### ISSUE THREAD

**Issue by gcappellini** [lululxvi/deepxde#609]
Dear @lululxvi,

My task is to implement the Heat Transfer Equation in a 2D square domain.

As BC, I would like the temperature to be constant on two sides of the square, and sinusoidal (**sin(t)**) on the other two sides. 

I expect the input x to be a 3-dimensional vector, therefore I tried expressing time as **x[: , 2:]**, but an error occurred (**arrays used as indices must be of integer (or boolean) type**). I think it's related to the fact that x is not defined before.

```
import deepxde as dde
import numpy as np

alpha = 1

def pde(x, y):
    dy_t = dde.grad.jacobian(y, x, i=0, j=1)
    dy_xx = dde.grad.hessian(y, x, i=0, j=0)
    dy_yy = dde.grad.hessian(y, x, i=1, j=1)
    return dy_t - alpha*dy_xx - alpha*dy_yy

geom = dde.geometry.Rectangle([0, 0], [1, 1])
timedomain = dde.geometry.TimeDomain(0, 0.99)
geomtime = dde.geometry.GeometryXTime(geom, timedomain)

def boundary_d(x, on_boundary):
        return on_boundary and np.isclose(x[1], 0)  
    
def boundary_l(x, on_boundary):
        return on_boundary and np.isclose(x[0], 0)

def boundary_r(x, on_boundary):
        return on_boundary and np.isclose(x[0], 1)
    
def boundary_u(x, on_boundary):
        return on_boundary and np.isclose(x[1], 1)

def func(x):
    return np.sin(x[:, 2:])    

bc_d = dde.icbc.DirichletBC(geomtime, func, boundary_d)
bc_l = dde.icbc.DirichletBC(geomtime, func, boundary_l)
bc_u = dde.icbc.DirichletBC(geomtime, lambda x: 0, lambda _, on_boundary: boundary_u)
bc_r = dde.icbc.DirichletBC(geomtime, lambda x: 0, lambda _, on_boundary: boundary_r)

ic = dde.icbc.IC(
     geomtime, lambda x: 0, lambda _, on_initial: on_initial
 )

data = dde.data.TimePDE(
    geomtime, pde, [bc_u, bc_r, bc_l, bc_d, ic], num_domain=2540, num_boundary=80, num_initial=160
)

net = dde.nn.FNN([3] + [20] * 3 + [1], "tanh", "Glorot normal")
model = dde.Model(data, net)

model.compile("adam", lr=1e-3)
model.train(epochs=15000)
model.compile("L-BFGS")
losshistory, train_state = model.train()
dde.saveplot(losshistory, train_state, issave=True, isplot=True)

```
Am I right? How can I overcome this problem?

Thank you

Guglielmo

**Comment by praksharma** [comment]
Hi, you have a small problem with your code, I know the error message is not that intuitive. When you define your BCs.
```python
bc_d = dde.icbc.DirichletBC(geomtime, func, boundary_d)
bc_l = dde.icbc.DirichletBC(geomtime, func, boundary_l)
bc_u = dde.icbc.DirichletBC(geomtime, lambda x: 0, lambda _, on_boundary: boundary_u)
bc_r = dde.icbc.DirichletBC(geomtime, lambda x: 0, lambda _, on_boundary: boundary_r)
```

This one `lambda _, on_boundary: boundary_u` and `lambda _, on_boundary: boundary_r` is problematic.  The reason is `boundary_u` and `boundary_r` are already functions. When you use `lambda` function over a function, it realises that the `boundary_u` is not sliceable because its not an array thus it gives you error that array indices must be integers.

So just replace this as follows:
```python
bc_d = dde.icbc.DirichletBC(geomtime, func, boundary_d)
bc_l = dde.icbc.DirichletBC(geomtime, func, boundary_l)
bc_u = dde.icbc.DirichletBC(geomtime, lambda x: 0, boundary_u)
bc_r = dde.icbc.DirichletBC(geomtime, lambda x: 0, boundary_r)
```

Hope it works.

**Comment by CZL-account** [comment]
Sometimes I wondered why must add ` lambda x_ ` this parameters, boundary conditions are clearly only a function. And I know deepxde is a very good framwork, but Its help documentation is really unfriendly.  I often have to rewrite PINNs by pytorch,  because my misuse. So I really hope you can Modify your help documentation, like opencv or pytorch. Then this framework will must be very popular.

**Comment by praksharma** [comment]
hey, `lambda` is just a way to define a function. If you don't like it, just use the normal funcions i.e. `def func():`. [This](https://deepxde.readthedocs.io/en/latest/demos/pinn_forward/poisson.1d.neumanndirichlet.html) example shows you how to use  both. In this example, `bc_l` is using a normal function. You can do the same with `bc_r` as follows:
```python
def func_r(x):
    return 2 * (x + 1)
bc_r = dde.icbc.NeumannBC(geom, func_r, boundary_r)
```
Hope this clarifies the usage of `lambda`. As far as the documentation is concerned. One has to maintain a balance between readability and providing enough details for various users with different levels of experience and expectations. I am just a user of DeepXDE like you, may not be the right person to comment on this.

**Comment by CZL-account** [comment]
Thank you very much , but my mean is why there are tow lambda functions in parameters
`bc_u = dde.icbc.DirichletBC(geomtime, lambda x: 0, lambda _, on_boundary: boundary_u)` ，
before {lambda_} there has already a {lambda x:0}，and when I click the source code, I only see one func parameter need to input in the function definition.

**Comment by praksharma** [comment]
First this is will give you a runtime error.
```python
bc_u = dde.icbc.DirichletBC(geomtime, lambda x: 0, lambda _, on_boundary: boundary_u)
```
Here boundary_u is a function, so you should directly use it. , instead of passing it to another function defined using `lambda`.
```python
bc_u = dde.icbc.DirichletBC(geomtime, lambda x: 0, boundary_u)
```

For of completeness let us see this boundary condition.
```python
bc_1 = dde.icbc.DirichletBC(geom, 
                               lambda x: 100, 
                               lambda x, on_boundary: on_boundary and np.isclose(x[1], 0)) 
```
Here the BC is 100 for all points with coordinates with y= 0 and on the boundary. We can write the same thing as follows:
```python
def BC_value(x):
    return 100
def BC_coordinates(x, on_boundary):
    return on_boundary and np.isclose(x[1], 0)
bc_1 = dde.icbc.DirichletBC(geom, BC_value, BC_coordinates)
```

You see both ways result in same thing.
