### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by yagizolmez** [lululxvi/deepxde#9]
Hi

I would be happy if you could specify the exact versions of dependencies (e.g. tensorflow x.x.x.)? I couldn't see them in the documentation and I am having lots of errors due to depreciated syntax of dependencies. I tried to go ahead and update the source code of the library to the current syntax, but it was just out of control.

Thanks
Yagiz

For example, this happens when running Volterra IDE example:

(deepxde_examples) yagiz@yagiz-ThinkPad-T460s:~/PycharmProjects/deepxde_examples$ python test_libraries.py
Traceback (most recent call last):
  File "test_libraries.py", line 64, in <module>
    main()
  File "test_libraries.py", line 45, in main
    net = dde.maps.FNN(layer_size, activation, initializer)
  File "/home/yagiz/anaconda3/envs/deepxde_examples/lib/python3.7/site-packages/deepxde/maps/fnn.py", line 32, in __init__
    self.kernel_initializer = initializers.get(kernel_initializer)
  File "/home/yagiz/anaconda3/envs/deepxde_examples/lib/python3.7/site-packages/deepxde/maps/initializers.py", line 93, in get
    "He normal": tf.variance_scaling_initializer(scale=2.0),
AttributeError: module 'tensorflow' has no attribute 'variance_scaling_initializer'

**Comment by chiefenne** [comment]
I see the same issue and came to the same conclusion. Currently tensorflow is at version 2.x which has even different keyword arguments for this call.

**Comment by lululxvi** [comment]
Sorry. The current code only supports 1.10 < tensorflow < 2.  I will upgrade using TF2, but I cannot guarantee the timeline. The warning from tf 1.14 is also due to different versions of tf, but can be ignored.

@chiefenne Which results obtained from 1.14 do you think can be wrong? I will have a look.

**Comment by chiefenne** [comment]
This is an example result for the Burgers_RAR.py

Python Anaconda Environment:
[conda_list.log](https://github.com/lululxvi/deepxde/files/3788296/conda_list.log)

Log file from the calculation:
[Burgers_RAR.log](https://github.com/lululxvi/deepxde/files/3788266/Burgers_RAR.log)

![2019-10-30 11_26_27-Figure 1](https://user-images.githubusercontent.com/6192662/67850230-4821de00-fb08-11e9-965e-1c1cbd494063.png)
![2019-10-30 11_26_36-Figure 3](https://user-images.githubusercontent.com/6192662/67850231-48ba7480-fb08-11e9-8340-218ede36de89.png)
![2019-10-30 11_26_32-Figure 2](https://user-images.githubusercontent.com/6192662/67850234-48ba7480-fb08-11e9-92ac-a7b476025aaa.png)

**Comment by lululxvi** [comment]
Acutally this is correct.

- Fig. 1. The jump of the loss is due to adding new residual points.
- Fig. 3. Because we don't give the solver the true solution, thus Fig. 3 can be ingored.
- Fig. 2. The solution is 3D, `(x, t, y)`, and here I just project the plot by removing the `t` dimension to plot in 2D. You can plot in 3D using the saved data.

**Comment by chiefenne** [comment]
Ok. Excellent. Thank you.

So I conclude the setup I have in my conda environment works.

**Comment by yagizolmez** [comment]
Hi, I have found something that might be useful for you. You can add the following to your code in order to make it compatible with TF2.
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

**Comment by lululxvi** [comment]
@yagizolmez Thank you for this nice suggestion. I will have a test.

**Comment by engsbk** [comment]
> Acutally this is correct.
> 
> * Fig. 1. The jump of the loss is due to adding new residual points.

Sometimes, I also see sudden fluctuations in the training process...
I winder if it's for the same reason.

```

5000      [4.28e-08, 2.57e-08, 9.32e-09]    [4.28e-08, 0.00e+00, 0.00e+00]    []  
6000      [4.36e-08, 1.17e-08, 3.89e-09]    [4.36e-08, 0.00e+00, 0.00e+00]    []  
7000      [3.91e-08, 6.11e-09, 2.11e-09]    [3.91e-08, 0.00e+00, 0.00e+00]    []  
**8000      [3.01e-07, 1.60e-04, 1.01e-04]    [3.01e-07, 0.00e+00, 0.00e+00]    []**  
9000      [1.48e-08, 1.40e-08, 9.21e-09]    [1.48e-08, 0.00e+00, 0.00e+00]    []  
10000     [9.31e-09, 1.78e-09, 2.02e-09]    [9.31e-09, 0.00e+00, 0.00e+00]    []  
11000     [5.05e-09, 1.39e-09, 1.72e-09]    [5.05e-09, 0.00e+00, 0.00e+00]    []  
```

**Comment by lululxvi** [comment]
It should be due to gradient descent.

**Comment by engsbk** [comment]
I'm asking about this because this is my output:

<img width="689" alt="Screen Shot 2021-01-19 at 10 55 38 AM" src="https://user-images.githubusercontent.com/25299510/105059042-e0c1b800-5a44-11eb-83ba-6cb67ac8c3dd.png">


I'm trying to implement a 1D wave equation with the IC :
```
#function for IC
def func(x):
    f_exact = 10
    return np.sin(2*np.pi*f_exact*x[:,1:2])
```

```

ic = dde.IC(
     geomtime, func, lambda _, on_initial: on_initial
)
```

```
def pde(x, u):
    c0 = 340
    #Using new DeepXDE Jacobians and Hessians
    du_xx = dde.grad.hessian(u, x, i=0, j=0)
    du_tt = dde.grad.hessian(u, x, i=1, j=1)
    return   du_xx - (1/c0 ** 2) * (du_tt)
```

These are my intervals.
```

geom = dde.geometry.Interval(0,100)
timedomain = dde.geometry.TimeDomain(0,1)
geomtime = dde.geometry.GeometryXTime(geom, timedomain)
```

I built a large FNN (256*50), I also doubled the training points I'm using:
```
folds = 2
data = dde.data.TimePDE(
    geomtime, pde, [bc, ic], 
    num_domain=int(folds*2540), 
    num_boundary=int(folds*80), 
    num_initial=int(folds*160)
)


```and I had to multiply my output with a very large number to see the results. 

Please advise as the results don't make sense to me.

**Comment by lululxvi** [comment]
- Is your IC correct? `x[:,1:2]` or `x[:,0:1]`?
- Rescale the PDE to make the interval from [0, 100] to [0, 1]. 
- Use hard constraint for IC. see the FAQ.
